language: cpp
compiler: clang
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.8-dev
install: true
script:
  - clang++ -g -std=c++14 main.cpp -o test
  - ./test
